---
spring:
  main:
    allow-bean-definition-overriding: true

  cloud:
    kubernetes:
      health:
        allow:
          enabled: false

  config:
    import:
    - classpath:./config/timeout-settings.properties
    - classpath:./config/game-settings.properties
    - classpath:./config/ui-settings.properties
#   - classpath:./config/*/  Does Not Work

---
server:
  port: 8080
management:
  endpoint:
      health:
        show-details: always
  endpoints:
    web:
      exposure:
        include: "*"