---
spring:
  config:
    import:
    - classpath:./config/timeout-settings.properties
---
server:
  port: 8080
management:
  endpoint:
      health:
        show-details: always
  endpoints:
    web:
      exposure:
        include: "*"