---
spring:
  config:
    import:
    - classpath:./config/timeout-settings.properties
    - classpath:./config/game-settings.properties
    - classpath:./config/ui-settings.properties
#   - classpath:./config/*/  Does Not Work

  cloud:
    kubernetes:
      config:
        name: config-as-properties
        sources:
        labels:
          version: 1.0.0
        
---
server:
  port: 8080
management:
  endpoint:
      health:
        show-details: always
  endpoints:
    web:
      exposure:
        include: "*"