---
spring:
  config:
    import:
    - classpath:./config/timeout-settings.properties
    #- optional:classpath:./config/*/
    #- classpath:./config/*/
    #- classpath:./config/timeout-settings.properties  Works    
    #- optional:classpath:/config/
    #- classpath:/config/
    #- classpath:./config/
    #- classpath:timeout-settings.properties  Works
---
server:
  port: 8080
management:
  endpoint:
      health:
        show-details: always
  endpoints:
    web:
      exposure:
        include: "*"