---
spring:
  config:
    import:
    - classpath:timeout-settings.properties
---
server:
  port: 8080
management:
  endpoint:
      health:
        show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
---
#timeout:
#  settings:
#    read-timeout-millis: 3333
#    connection-timeout-millis: 4444