---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: spring-cloud-kubernetes-consumer-service
      name: spring-cloud-kubernetes-consumer-service
    spec:
      ports:
        - name: http
          port: 8080
          targetPort: 8080
      selector:
        app: spring-cloud-kubernetes-consumer-service
      type: ClusterIP
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: spring-cloud-kubernetes-consumer-service
      name: spring-cloud-kubernetes-consumer-service
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        app: spring-cloud-kubernetes-consumer-service
      name: spring-cloud-kubernetes-consumer-service:view
    roleRef:
      kind: Role
      apiGroup: rbac.authorization.k8s.io
      name: namespace-reader
    subjects:
      - kind: ServiceAccount
        name: spring-cloud-kubernetes-consumer-service
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      namespace: default
      name: namespace-reader
    rules:
      - apiGroups: ["", "extensions", "apps"]
        resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
        verbs: ["get", "list", "watch"]
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: spring-cloud-kubernetes-consumer-service-deployment
    spec:
      selector:
        matchLabels:
          app: spring-cloud-kubernetes-consumer-service
      template:
        metadata:
          labels:
            app: spring-cloud-kubernetes-consumer-service
        spec:
          serviceAccount: spring-cloud-kubernetes-consumer-service
          containers:
          - name: spring-cloud-kubernetes-consumer-service
            image: springcloud/spring-cloud-kubernetes-consumer-service:3.3.0-SNAPSHOT
            imagePullPolicy: IfNotPresent
            env:
              - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES_CONFIGURATION_WATCHER
                value: DEBUG
              - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES_CLIENT_CONFIG_RELOAD
                value: DEBUG
              - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES_COMMONS_CONFIG_RELOAD
                value: DEBUG
              - name: SPRING_CLOUD_KUBERNETES_CONFIGURATION_WATCHER_REFRESHDELAY
                value: "10"                
            readinessProbe:
              httpGet:
                port: 8080
                path: /actuator/health/readiness
            livenessProbe:
              httpGet:
                port: 8080
                path: /actuator/health/liveness
            ports:
            - containerPort: 8080
            volumeMounts:
            - name: log-volume
              mountPath: /workspace/logs          
          volumes:
          - name: log-volume
            emptyDir: {}