---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: spring-cloud-kubernetes-consumer-service
      name: spring-cloud-kubernetes-consumer-service
    spec:
      ports:
        - name: http
          port: 8080
          targetPort: 8080
      selector:
        app: spring-cloud-kubernetes-consumer-service
      type: ClusterIP

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: spring-cloud-kubernetes-consumer-service-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: spring-cloud-kubernetes-consumer-service
      template:
        metadata:
          labels:
            app: spring-cloud-kubernetes-consumer-service
        spec:
          serviceAccount: spring-cloud-kubernetes-consumer-service

          securityContext:
              runAsUser: 1002
              runAsGroup: 1000
              fsGroup: 1000  # Ensure this matches runAsGroup              

          initContainers:
          - name: take-data-dir-ownership
            image: alpine:3
            # Give 'cnb:1000' user (id cnb is 1002) 1000 is eric permissions a mounted volume      
            command:
            - chown
            - -R
            - 1002:1000
            - /data
            command:
            - ls
            - -latr
            - /data
            volumeMounts:
            - name: data-dir
              mountPath: /data

          containers:
          - name: spring-cloud-kubernetes-consumer-service
            image: ericm24/spring-cloud-kubernetes-consumer-service:3.3.6-SNAPSHOT
            imagePullPolicy: IfNotPresent

            env:
              - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD
                value: DEBUG
              - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BEANS
                value: DEBUG
              - name: LOGGING_LEVEL_COM_ERIC                
                value: DEBUG
              - name: SPRING_CONFIG_IMPORT
                value: "optional:file:/workspace/configs/timeout-settings.properties,optional:file:/workspace/configs/game-settings.properties,optional:file:/workspace/configs/ui-settings.properties"
            readinessProbe:
              httpGet:
                port: 8080
                path: /actuator/health/readiness
            livenessProbe:
              httpGet:
                port: 8080
                path: /actuator/health/liveness
            ports:
            - containerPort: 8080

            volumeMounts:
            - name: pvc-consumer-service-logs
              mountPath: "/workspace/logs"
            - name: pvc-consumer-service-configs
              mountPath: "/workspace/configs"
#            - name: empty-log-volume
#              mountPath: "/data/logs"

          volumes:
          - name: pvc-consumer-service-logs
            persistentVolumeClaim:
              claimName: pvc-spring-logs-nfs
          - name: pvc-consumer-service-configs
            persistentVolumeClaim:
              claimName: pvc-spring-configs-nfs
#          - name: empty-log-volume
#            emptyDir: {}          
          - name: data-dir
            hostPath:
              path: /mnt/nfsshare/k8svolumes/data



